package com.example.books.util;

/**
 * Created by My on 07.10.2014 г..
 */
public enum StatusCode {
    FATAL_ERROR, JSON_MESSAGE, SUCCESS, ERROR, NETWOR_UNAVAILABLE,
    SIGN_IN_INVALID_EMAIL, SIGN_IN_EMPTY_PASSWORD,
    SIGN_UP_INVALID_EMAIL, SIGN_UP_INVALID_FULLNAME, SIGN_UP_ARE_NOT_BOTH_PASSWORDS_FILLED, SIGN_UP_ARE_NOT_PASSWORDS_EQUAL,
    ADD_BOOK_ALREADY_ADDED
}
